In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_excel("OLA Bookings-100000-Rows.xlsx")

In [5]:
df.head(20)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,0.583333,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,0.930556,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,0.832639,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,0.135417,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,0.376389,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
5,2024-07-13 04:42:00,0.195833,CNR8787177882,Success,CID802429,Mini,Kadugodi,Vijayanagar,231.0,90.0,NaN,NaN,No,NaN,173,UPI,41,3.4,4.6,https://cdn-icons-png.flaticon.com/128/3202/32...
6,2024-07-23 09:51:00,0.410417,CNR3612067560,Success,CID476071,Bike,Tumkur Road,Whitefield,133.0,40.0,NaN,NaN,No,NaN,140,Cash,49,3.2,4.5,https://cdn-icons-png.flaticon.com/128/9983/99...
7,2024-07-11 11:12:00,0.466667,CNR5374902489,Canceled by Driver,CID735691,Prime Plus,Bannerghatta Road,Sarjapur Road,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,344,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/11409/1...
8,2024-07-01 19:19:00,0.804861,CNR5030602354,Driver Not Found,CID999840,Mini,Chamarajpet,Peenya,NaN,NaN,NaN,NaN,NaN,NaN,839,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/3202/32...
9,2024-07-18 01:31:00,0.063194,CNR6328453219,Canceled by Driver,CID907133,Auto,RT Nagar,Varthur,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,893,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/16526/1...
10,2024-07-29 23:33:00,0.981250,CNR4787583516,Success,CID923404,Prime Plus,Hosur Road,Jayanagar,35.0,55.0,NaN,NaN,No,NaN,164,Cash,46,4.5,3.4,https://cdn-icons-png.flaticon.com/128/11409/1...
11,2024-07-26 04:03:00,0.168750,CNR7943634301,Success,CID647026,Prime Plus,Kammanahalli,Rajajinagar,238.0,95.0,NaN,NaN,No,NaN,399,Cash,18,3.9,4.4,https://cdn-icons-png.flaticon.com/128/11409/1...
12,2024-07-27 13:18:00,0.554167,CNR4524472111,Success,CID540929,Auto,Cox Town,Yelahanka,126.0,35.0,NaN,NaN,No,NaN,330,UPI,8,3.0,4.8,https://cdn-icons-png.flaticon.com/128/16526/1...
13,2024-07-17 18:55:00,0.788194,CNR3914552212,Canceled by Driver,CID557845,Auto,Hosur Road,Banashankari,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,427,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/16526/1...
14,2024-07-16 09:54:00,0.412500,CNR8181602032,Success,CID167642,Bike,Indiranagar,MG Road,70.0,95.0,NaN,NaN,No,NaN,378,UPI,18,4.8,4.1,https://cdn-icons-png.flaticon.com/128/9983/99...
15,2024-07-02 10:25:00,0.434028,CNR8090918544,Success,CID640151,Bike,Magadi Road,HSR Layout,126.0,95.0,NaN,NaN,No,NaN,343,UPI,23,3.7,3.6,https://cdn-icons-png.flaticon.com/128/9983/99...
16,2024-07-02 23:50:00,0.993056,CNR3211335290,Driver Not Found,CID630354,Mini,Ramamurthy Nagar,BTM Layout,NaN,NaN,NaN,NaN,NaN,NaN,366,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/3202/32...
17,2024-07-05 23:42:00,0.987500,CNR3196156650,Success,CID243275,Bike,Electronic City,Langford Town,140.0,40.0,NaN,NaN,No,NaN,401,Cash,8,3.3,3.9,https://cdn-icons-png.flaticon.com/128/9983/99...
18,2024-07-09 11:11:00,0.465972,CNR9975925287,Success,CID162055,Prime SUV,Magadi Road,RT Nagar,42.0,30.0,NaN,NaN,No,NaN,343,UPI,17,3.0,3.8,https://cdn-icons-png.flaticon.com/128/9983/99...
19,2024-07-12 14:44:00,0.613889,CNR1591113431,Success,CID902781,eBike,Koramangala,Sarjapur Road,245.0,70.0,NaN,NaN,No,NaN,2014,Cash,33,4.2,4.9,https://cdn-icons-png.flaticon.com/128/6839/68...

In [6]:
print(df)

                      Date      Time     Booking_ID        Booking_Status  \
0      2024-07-26 14:00:00  0.583333  CNR7153255142    Canceled by Driver
1      2024-07-25 22:20:00  0.930556  CNR2940424040               Success
2      2024-07-30 19:59:00  0.832639  CNR2982357879               Success
3      2024-07-22 03:15:00  0.135417  CNR2395710036  Canceled by Customer
4      2024-07-02 09:02:00  0.376389  CNR1797421769               Success
...                    ...       ...            ...                   ...
103019 2024-07-31 09:06:00  0.379167  CNR9488489435               Success
103020 2024-07-31 15:12:00  0.633333  CNR3151743100               Success
103021 2024-07-31 13:59:00  0.582639  CNR1286151233               Success
103022 2024-07-31 14:56:00  0.622222  CNR2027162035               Success
103023 2024-07-31 13:57:00  0.581250  CNR9770709721               Success

       Customer_ID Vehicle_Type    Pickup_Location  Drop_Location  V_TAT  \
0        CID713523  Prime Sedan        Tumkur Road       RT Nagar    NaN
1        CID225428         Bike        Magadi Road        Varthur  203.0
2        CID270156    Prime SUV      Sahakar Nagar        Varthur  238.0
3        CID581320        eBike         HSR Layout    Vijayanagar    NaN
4        CID939555         Mini        Rajajinagar    Chamarajpet  252.0
...            ...          ...                ...            ...    ...
103019   CID371654   Prime Plus      Richmond Town        Varthur  245.0
103020   CID334158         Auto        Vijayanagar  Richmond Town   84.0
103021   CID113188    Prime SUV  Bannerghatta Road       JP Nagar   35.0
103022   CID118301        eBike        Indiranagar    Magadi Road  210.0
103023   CID217959         Auto             Ulsoor         Hennur  175.0

        C_TAT                    Canceled_Rides_by_Customer  \
0         NaN                                           NaN
1        30.0                                           NaN
2       130.0                                           NaN
3         NaN  Driver is not moving towards pickup location
4        80.0                                           NaN
...       ...                                           ...
103019   35.0                                           NaN
103020  145.0                                           NaN
103021   75.0                                           NaN
103022  140.0                                           NaN
103023  125.0                                           NaN

            Canceled_Rides_by_Driver Incomplete_Rides Incomplete_Rides_Reason  \
0       Personal & Car related issue              NaN                     NaN
1                                NaN               No                     NaN
2                                NaN               No                     NaN
3                                NaN              NaN                     NaN
4                                NaN               No                     NaN
...                              ...              ...                     ...
103019                           NaN               No                     NaN
103020                           NaN               No                     NaN
103021                           NaN               No                     NaN
103022                           NaN               No                     NaN
103023                           NaN               No                     NaN

        Booking_Value Payment_Method  Ride_Distance  Driver_Ratings  \
0                 444            NaN              0             NaN
1                 158           Cash             13             4.1
2                 386            UPI             40             4.2
3                 384            NaN              0             NaN
4                 822    Credit Card             45             4.0
...               ...            ...            ...             ...
103019            111           Cash             41             3.6
103020           1097            UPI             17             4.3
103021           2201           Cash             37             3.6
103022            267            UPI             47             3.4
103023            462            UPI              3             4.8

        Customer_Rating                                     Vehicle Images
0                   NaN  https://cdn-icons-png.flaticon.com/128/14183/1...
1                   4.0  https://cdn-icons-png.flaticon.com/128/9983/99...
2                   4.8  https://cdn-icons-png.flaticon.com/128/9983/99...
3                   NaN  https://cdn-icons-png.flaticon.com/128/6839/68...
4                   3.0  https://cdn-icons-png.flaticon.com/128/3202/32...
...                 ...                                                ...
103019              3.8  https://cdn-icons-png.flaticon.com/128/11409/1...
103020              3.3  https://cdn-icons-png.flaticon.com/128/16526/1...
103021              3.2  https://cdn-icons-png.flaticon.com/128/9983/99...
103022              3.1  https://cdn-icons-png.flaticon.com/128/6839/68...
103023              4.4  https://cdn-icons-png.flaticon.com/128/16526/1...

[103024 rows x 20 columns]

In [7]:
print(df)

                      Date      Time     Booking_ID        Booking_Status  \
0      2024-07-26 14:00:00  0.583333  CNR7153255142    Canceled by Driver
1      2024-07-25 22:20:00  0.930556  CNR2940424040               Success
2      2024-07-30 19:59:00  0.832639  CNR2982357879               Success
3      2024-07-22 03:15:00  0.135417  CNR2395710036  Canceled by Customer
4      2024-07-02 09:02:00  0.376389  CNR1797421769               Success
...                    ...       ...            ...                   ...
103019 2024-07-31 09:06:00  0.379167  CNR9488489435               Success
103020 2024-07-31 15:12:00  0.633333  CNR3151743100               Success
103021 2024-07-31 13:59:00  0.582639  CNR1286151233               Success
103022 2024-07-31 14:56:00  0.622222  CNR2027162035               Success
103023 2024-07-31 13:57:00  0.581250  CNR9770709721               Success

       Customer_ID Vehicle_Type    Pickup_Location  Drop_Location  V_TAT  \
0        CID713523  Prime Sedan        Tumkur Road       RT Nagar    NaN
1        CID225428         Bike        Magadi Road        Varthur  203.0
2        CID270156    Prime SUV      Sahakar Nagar        Varthur  238.0
3        CID581320        eBike         HSR Layout    Vijayanagar    NaN
4        CID939555         Mini        Rajajinagar    Chamarajpet  252.0
...            ...          ...                ...            ...    ...
103019   CID371654   Prime Plus      Richmond Town        Varthur  245.0
103020   CID334158         Auto        Vijayanagar  Richmond Town   84.0
103021   CID113188    Prime SUV  Bannerghatta Road       JP Nagar   35.0
103022   CID118301        eBike        Indiranagar    Magadi Road  210.0
103023   CID217959         Auto             Ulsoor         Hennur  175.0

        C_TAT                    Canceled_Rides_by_Customer  \
0         NaN                                           NaN
1        30.0                                           NaN
2       130.0                                           NaN
3         NaN  Driver is not moving towards pickup location
4        80.0                                           NaN
...       ...                                           ...
103019   35.0                                           NaN
103020  145.0                                           NaN
103021   75.0                                           NaN
103022  140.0                                           NaN
103023  125.0                                           NaN

            Canceled_Rides_by_Driver Incomplete_Rides Incomplete_Rides_Reason  \
0       Personal & Car related issue              NaN                     NaN
1                                NaN               No                     NaN
2                                NaN               No                     NaN
3                                NaN              NaN                     NaN
4                                NaN               No                     NaN
...                              ...              ...                     ...
103019                           NaN               No                     NaN
103020                           NaN               No                     NaN
103021                           NaN               No                     NaN
103022                           NaN               No                     NaN
103023                           NaN               No                     NaN

        Booking_Value Payment_Method  Ride_Distance  Driver_Ratings  \
0                 444            NaN              0             NaN
1                 158           Cash             13             4.1
2                 386            UPI             40             4.2
3                 384            NaN              0             NaN
4                 822    Credit Card             45             4.0
...               ...            ...            ...             ...
103019            111           Cash             41             3.6
103020           1097            UPI             17             4.3
103021           2201           Cash             37             3.6
103022            267            UPI             47             3.4
103023            462            UPI              3             4.8

        Customer_Rating                                     Vehicle Images
0                   NaN  https://cdn-icons-png.flaticon.com/128/14183/1...
1                   4.0  https://cdn-icons-png.flaticon.com/128/9983/99...
2                   4.8  https://cdn-icons-png.flaticon.com/128/9983/99...
3                   NaN  https://cdn-icons-png.flaticon.com/128/6839/68...
4                   3.0  https://cdn-icons-png.flaticon.com/128/3202/32...
...                 ...                                                ...
103019              3.8  https://cdn-icons-png.flaticon.com/128/11409/1...
103020              3.3  https://cdn-icons-png.flaticon.com/128/16526/1...
103021              3.2  https://cdn-icons-png.flaticon.com/128/9983/99...
103022              3.1  https://cdn-icons-png.flaticon.com/128/6839/68...
103023              4.4  https://cdn-icons-png.flaticon.com/128/16526/1...

[103024 rows x 20 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[ns]
 1   Time                        103024 non-null  float64
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   object
 11  Canceled_Rides_by_Driver    18434 non-null   object
 12  Incomplete_Rides            63967 non-null   object
 13  Incomplete_Rides_Reason     3926 non-null    object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(2), object(12)
memory usage: 15.7+ MB

In [9]:
df.describe()

,Date,Time,V_TAT,C_TAT,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating
count,103024,103024.000000,63967.000000,63967.000000,103024.000000,103024.000000,63967.000000,63967.000000
mean,2024-07-16 11:31:38.879678720,0.499045,170.876952,84.873372,548.751883,14.189927,3.997457,3.998313
min,2024-07-01 00:00:00,0.000000,35.000000,25.000000,100.000000,0.000000,3.000000,3.000000
25%,2024-07-08 18:41:00,0.250694,98.000000,55.000000,242.000000,0.000000,3.500000,3.500000
50%,2024-07-16 11:23:00,0.498611,168.000000,85.000000,386.000000,8.000000,4.000000,4.000000
75%,2024-07-24 05:18:00,0.747917,238.000000,115.000000,621.000000,26.000000,4.500000,4.500000
max,2024-07-31 23:58:00,0.999306,308.000000,145.000000,2999.000000,49.000000,5.000000,5.000000
std,NaN,0.288235,80.803640,36.005100,536.541221,15.776270,0.576834,0.578957

In [10]:
df.tail()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
103019,2024-07-31 09:06:00,0.379167,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,0.633333,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,0.582639,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,0.622222,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,0.581250,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [11]:
df.count()

Date                          103024
Time                          103024
Booking_ID                    103024
Booking_Status                103024
Customer_ID                   103024
Vehicle_Type                  103024
Pickup_Location               103024
Drop_Location                 103024
V_TAT                          63967
C_TAT                          63967
Canceled_Rides_by_Customer     10499
Canceled_Rides_by_Driver       18434
Incomplete_Rides               63967
Incomplete_Rides_Reason         3926
Booking_Value                 103024
Payment_Method                 63967
Ride_Distance                 103024
Driver_Ratings                 63967
Customer_Rating                63967
Vehicle Images                103024
dtype: int64

In [12]:
# Retrieve all successful bookings:#
df[df["Booking_Status"]=="Success"]

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
1,2024-07-25 22:20:00,0.930556,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,0.832639,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
4,2024-07-02 09:02:00,0.376389,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
5,2024-07-13 04:42:00,0.195833,CNR8787177882,Success,CID802429,Mini,Kadugodi,Vijayanagar,231.0,90.0,NaN,NaN,No,NaN,173,UPI,41,3.4,4.6,https://cdn-icons-png.flaticon.com/128/3202/32...
6,2024-07-23 09:51:00,0.410417,CNR3612067560,Success,CID476071,Bike,Tumkur Road,Whitefield,133.0,40.0,NaN,NaN,No,NaN,140,Cash,49,3.2,4.5,https://cdn-icons-png.flaticon.com/128/9983/99...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 09:06:00,0.379167,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,0.633333,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,0.582639,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,0.622222,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,0.581250,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [13]:
df.isnull().sum()

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
Incomplete_Rides              39057
Incomplete_Rides_Reason       99098
Booking_Value                     0
Payment_Method                39057
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
Vehicle Images                    0
dtype: int64

In [14]:
#null values fill krna#
df["V_TAT"]=df["V_TAT"].fillna(df["V_TAT"].mean())
df["C_TAT"]=df["C_TAT"].fillna(df["C_TAT"].mean())
df["Canceled_Rides_by_Customer"]=df["Canceled_Rides_by_Customer"].fillna(df["Canceled_Rides_by_Customer"].mode()[0])
df["Canceled_Rides_by_Driver"]=df["Canceled_Rides_by_Driver"].fillna(df["Canceled_Rides_by_Driver"].mode()[0])
df["Incomplete_Rides"]=df["Incomplete_Rides"].fillna(df["Incomplete_Rides"].mode()[0])
df["Incomplete_Rides_Reason"]=df["Incomplete_Rides_Reason"].fillna(df["Incomplete_Rides_Reason"].mode()[0])
df["Payment_Method"]=df["Payment_Method"].fillna(df["Payment_Method"].mode()[0])
df["Driver_Ratings"]=df["Driver_Ratings"].fillna(df["Driver_Ratings"].mean())
df["Customer_Rating"]=df["Customer_Rating"].fillna(df["Customer_Rating"].mean())

In [15]:
df.isnull().sum()

Date                          0
Time                          0
Booking_ID                    0
Booking_Status                0
Customer_ID                   0
Vehicle_Type                  0
Pickup_Location               0
Drop_Location                 0
V_TAT                         0
C_TAT                         0
Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides              0
Incomplete_Rides_Reason       0
Booking_Value                 0
Payment_Method                0
Ride_Distance                 0
Driver_Ratings                0
Customer_Rating               0
Vehicle Images                0
dtype: int64

In [16]:
df[df["Booking_Status"]=="Success"]

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
1,2024-07-25 22:20:00,0.930556,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,0.832639,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
4,2024-07-02 09:02:00,0.376389,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
5,2024-07-13 04:42:00,0.195833,CNR8787177882,Success,CID802429,Mini,Kadugodi,Vijayanagar,231.0,90.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,173,UPI,41,3.4,4.6,https://cdn-icons-png.flaticon.com/128/3202/32...
6,2024-07-23 09:51:00,0.410417,CNR3612067560,Success,CID476071,Bike,Tumkur Road,Whitefield,133.0,40.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,140,Cash,49,3.2,4.5,https://cdn-icons-png.flaticon.com/128/9983/99...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 09:06:00,0.379167,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,0.633333,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,0.582639,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,0.622222,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,0.581250,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,Driver is not moving towards pickup location,Personal & Car related issue,No,Customer Demand,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [17]:
 #Find the average ride distance for each vehicle type:
avg_distance = df.groupby("Vehicle_Type")["Ride_Distance"].mean()

In [18]:
print(avg_distance)

Vehicle_Type
Auto            6.238089
Bike           15.533079
Mini           15.510102
Prime Plus     15.447474
Prime SUV      15.274514
Prime Sedan    15.764939
eBike          15.580589
Name: Ride_Distance, dtype: float64

In [19]:
#. Get the total number of cancelled rides by customers:
total_cancelled = (df["Booking_Status"] == "Canceled_Rides_by_Customer").sum()

print("\nTotal Cancelled Rides by Customers:", total_cancelled)

Total Cancelled Rides by Customers: 0

In [20]:
 #List the top 5 customers who booked the highest number of rides:
# Top 5 customers who booked the highest number of rides

top_5_customers = (df.groupby("Customer_ID").size().reset_index(name="Total_Rides").sort_values("Total_Rides", ascending=False).head(5))

print(top_5_customers)

      Customer_ID  Total_Rides
89695   CID954071            5
17605   CID268274            4
17111   CID263459            4
9388    CID189965            4
30150   CID387617            4

In [22]:
top_10_customer =(df.groupby("Customer_ID").size().reset_index(name="total_rides").sort_values("total_rides",ascending=False).head(10))
print(top_10_customer)

      Customer_ID  total_rides
89695   CID954071            5
17605   CID268274            4
17111   CID263459            4
9388    CID189965            4
30150   CID387617            4
17416   CID266327            4
10387   CID199017            4
24062   CID329193            4
25291   CID340854            4
38179   CID465260            4

In [23]:
#Get the number of rides cancelled by drivers due to personal and car-related issues
rides_cancelled = (df["Canceled_Rides_by_Driver"]=="Personal & Car related issue").sum()
print(" the number of rides cancelled by drivers due to personal and car-related issues:",rides_cancelled)

 the number of rides cancelled by drivers due to personal and car-related issues: 91132

In [24]:
#Find the maximum and minimum driver ratings for Prime Sedan bookings:
# Filter Prime Sedan bookings
prime_sedan = df[df["Vehicle_Type"] == "Prime Sedan"]

# Maximum and Minimum Driver Rating
max_rating = prime_sedan["Driver_Ratings"].max()
min_rating = prime_sedan["Driver_Ratings"].min()

print("Maximum Driver Rating:", max_rating)
print("Minimum Driver Rating:", min_rating)

Maximum Driver Rating: 5.0
Minimum Driver Rating: 3.0

In [25]:
#. Retrieve all rides where payment was made using UPI:
total_UPI = (df["Payment_Method"] == "UPI").sum()

print("\nTotal Numbers of UPI pay:", total_UPI)

Total Numbers of UPI pay: 25881

In [26]:
#. Find the average customer rating per vehicle type
avg_cutomer_rating = df.groupby("Vehicle_Type")["Customer_Rating"].mean()
print("avg_cutomer_rating",avg_cutomer_rating )

avg_cutomer_rating Vehicle_Type
Auto           3.998622
Bike           3.995238
Mini           3.997952
Prime Plus     4.005215
Prime SUV      3.998967
Prime Sedan    4.000378
eBike          3.991833
Name: Customer_Rating, dtype: float64

In [27]:
#Calculate the total booking value of rides completed successfully
total_successful_booking=(df["Booking_Status"]=="Success").sum()
print("\ntotal_successful_booking:",total_successful_booking)

total_successful_booking: 63967

In [28]:
#List all incomplete rides along with the reason
incomplete_rides=(df["Incomplete_Rides"]=="Yes").sum()
print(incomplete_rides)

3926

In [29]:
# List all incomplete rides along with the reason

incomplete_rides = df[
    df["Incomplete_Rides"] == "Yes"][["Incomplete_Rides", "Incomplete_Rides_Reason"]]

print(incomplete_rides)

       Incomplete_Rides Incomplete_Rides_Reason
38                  Yes         Customer Demand
49                  Yes       Vehicle Breakdown
70                  Yes         Customer Demand
93                  Yes             Other Issue
101                 Yes             Other Issue
...                 ...                     ...
102859              Yes         Customer Demand
102870              Yes       Vehicle Breakdown
102973              Yes       Vehicle Breakdown
102978              Yes       Vehicle Breakdown
103011              Yes             Other Issue

[3926 rows x 2 columns]

In [6]:
df.corr(numeric_only=True)

,Time,V_TAT,C_TAT,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating
Time,1.000000,0.005051,0.000618,-0.007190,-0.005111,-0.003434,0.004010
V_TAT,0.005051,1.000000,0.000249,-0.003671,-0.011204,-0.002300,0.000574
C_TAT,0.000618,0.000249,1.000000,-0.004443,0.000074,-0.002815,0.001015
Booking_Value,-0.007190,-0.003671,-0.004443,1.000000,0.000492,-0.001327,0.006231
Ride_Distance,-0.005111,-0.011204,0.000074,0.000492,1.000000,-0.007235,0.009871
Driver_Ratings,-0.003434,-0.002300,-0.002815,-0.001327,-0.007235,1.000000,-0.002807
Customer_Rating,0.004010,0.000574,0.001015,0.006231,0.009871,-0.002807,1.000000

In [7]:
df.to_excel("clean_OLA.xlsx", index=False)